name: Publish Site

on:
  workflow_dispatch:
  push:
    branches:
      - develop

permissions:
  contents: read

concurrency:
  group: 'pages'
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - uses: actions/setup-node@v3
        with:
          node-version: 20.11.0
      - run: corepack enable
      - run: npm run setup:pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Build Deps
        run: pnpm build

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v1.0.9
        with:
          path: build/

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v2
